# Generated by Django 3.0.8 on 2020-07-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20200701_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='op_chara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op', to='memo.Character'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='my_chara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my', to='memo.Character'),
        ),
    ]
