# Generated by Django 3.0.8 on 2020-07-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20200701_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
