# Generated by Django 3.0.8 on 2020-07-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_auto_20200703_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='datetime',
        ),
    ]
