# Generated by Django 3.0.8 on 2020-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0006_auto_20200703_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
